<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Webpatser\Uuid\Uuid;

class Page extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'uuid',
        'title_km',
        'title_en',
        'type',
        'active',
        'content_km',
        'content_en',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = (string)Uuid::generate(4);
        });
    }
}
